In [ ]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
file_path = "../data/Raw/furniture_returns_uncleaned.xlsx"

df = pd.read_excel(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 5195
Number of columns: 12

In [4]:
df.head(10)

,Return ID,Product,Value ₹,Transit Days,Return Reason,Condition Hint,Severity,Safety,SLA hrs,Inspection Outcome,Resale Before ₹,Resale After ₹
0,R-3047,Bed,46133,unknown,size issue,No Visible Damage,NaN,Low,24,No Defect,42005,40807
1,R2886,Bed,40964,2,Damaged,Torn Fabric,Moderate,High,Rs.72,Repairable,38015,26638
2,R2747,NaN,24559,1,Damaged,chipped surface,Moderate,Low,48,MINOR DAMAGE,19062,16701
3,R4670,Dining Table,"₹24,570",1,Defective,Loose Joints,MINOR,Low,48,Minor Damage,unknown,17960
4,R4898,Dining Table,"33,047",0,Not as Expected,Color Mismatch,minor,Low,48,Minor Damage,29705,"27,766"
5,R2596,Bed,43374,0,Defective,faulty hinge,Severe,high,72,Repairable,37756,"30,581"
6,R3729,Sofa,47719,0,Damaged,CHIPPED SURFACE,Severe,Medium,48,Scrap,42758,24459
7,R3755,WARDROBE,"24,353",6,Defective,Cushion Damage,Minor,Medium,72,Minor Damage,20744,19608
8,R3354,Coffee Table,Rs.11203,7,Defective,Cushion Damage,MODERATE,NaN,72,REPAIRABLE,10240,7245
9,r79,Chair,"₹5,173",NaN,Wrong Product,No Visible Damage,None,LOW,72,No Defect,4003,3989

In [5]:
df.tail()

,Return ID,Product,Value ₹,Transit Days,Return Reason,Condition Hint,Severity,Safety,SLA hrs,Inspection Outcome,Resale Before ₹,Resale After ₹
5190,R4308,Bed,Rs.51800,1,not as expected,Wrong Fabric,Minor,Low,72,Minor Damage,43341,39580
5191,R2551,Coffee Table,14833,4,Size Issue,no visible damage,NaN,Low,72,No Defect,13145,12838
5192,R0538,Bookshelf,12918,1,Wrong Product,No Visible Damage,NaN,Low,24,No Defect,11947,11886
5193,R1221,Dining Table,33188.0,1,DEFECTIVE,Door Misalignment,Moderate,Medium,72,Minor Damage,29557,25895
5194,R4272,Wardrobe,"28,348",0,wrong product,No Visible Damage,NaN,Low,72,No Defect,25296,24708.00

In [6]:
print("Column names:")

for column in df.columns:
    print("-", column)

Column names:
- Return ID
- Product
- Value ₹
- Transit Days
- Return Reason
- Condition Hint
- Severity
- Safety
- SLA hrs
- Inspection Outcome
- Resale Before ₹
- Resale After ₹

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5195 entries, 0 to 5194
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Return ID           5180 non-null   object
 1   Product             5092 non-null   object
 2   Value ₹             5067 non-null   object
 3   Transit Days        5073 non-null   object
 4   Return Reason       5094 non-null   object
 5   Condition Hint      5081 non-null   object
 6   Severity            3858 non-null   object
 7   Safety              5059 non-null   object
 8   SLA hrs             5087 non-null   object
 9   Inspection Outcome  5096 non-null   object
 10  Resale Before ₹     5089 non-null   object
 11  Resale After ₹      5085 non-null   object
dtypes: object(12)
memory usage: 487.2+ KB

In [18]:
missing_data = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_data.sort_values(
    "Missing Count",
    ascending=False
)

                    Missing Count  Missing Percentage
Severity                     1337               25.74
Safety                        136                2.62
Value ₹                       128                2.46
Transit Days                  122                2.35
Condition Hint                114                2.19
Resale After ₹                110                2.12
SLA hrs                       108                2.08
Resale Before ₹               106                2.04
Product                       103                1.98
Return Reason                 101                1.94
Inspection Outcome             99                1.91
Return ID                      15                0.29

In [19]:
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 2479

In [20]:
duplicate_rows = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_rows)

Exact duplicate rows: 137

In [21]:
duplicate_ids = df["Return ID"].duplicated().sum()

print("Duplicate Return IDs:", duplicate_ids)

Duplicate Return IDs: 138

In [22]:
duplicate_records = df[
    df["Return ID"].duplicated(keep=False)
].sort_values("Return ID")

duplicate_records

,Return ID,Product,Value ₹,Transit Days,Return Reason,Condition Hint,Severity,Safety,SLA hrs,Inspection Outcome,Resale Before ₹,Resale After ₹
4319,R0637,Dining Table,34820,6,Defective,Door Misalignment,Severe,High,48,Major Damage,32134.00,20619
1682,R0637,Dining Table,34820,6,Defective,Door Misalignment,Severe,High,48,Major Damage,32134.00,20619
653,R1356,Bookshelf,7997,11,NaN,Scratched Surface,Severe,High,NaN,SCRAP,6424,3697.00
3191,R1356,Bookshelf,7997,11,NaN,Scratched Surface,Severe,High,NaN,SCRAP,6424,3697.00
5139,R1866,DINING TABLE,33517,2,NOT AS EXPECTED,Color Mismatch,Minor,LOW,72,minor damage,25690,23240
...,...,...,...,...,...,...,...,...,...,...,...,...
3448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
categorical_columns = [
    "Product",
    "Return Reason",
    "Condition Hint",
    "Severity",
    "Safety",
    "Inspection Outcome"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].value_counts(dropna=False).head(10))

Product
Product
Bed             563
Chair           562
Bookshelf       562
Sofa            533
Dining Table    532
Wardrobe        524
Coffee Table    518
NaN             103
dining table     52
CHAIR            50
Name: count, dtype: int64

Return Reason
Return Reason
Damaged            661
Defective          625
Wrong Product      586
Size Issue         558
Not as Expected    519
WRONG PRODUCT      116
defective          114
DEFECTIVE          106
damaged            103
NaN                101
Name: count, dtype: int64

Condition Hint
Condition Hint
No Visible Damage      1179
Minor Scratch           208
no visible damage       200
NO VISIBLE DAMAGE       198
Wrong Fabric            183
Color Mismatch          177
Broken Frame            156
No Visible Damage       149
Door Misalignment       147
Cushion Damage          123
Name: count, dtype: int64

Severity
Severity
NaN         1337
Minor        897
Moderate     486
Severe       468
NONE         194
none         190
MINOR        165
None         140
 None        137
minor        135
Name: count, dtype: int64

Safety
Safety
Low       2211
Medium     451
High       434
LOW        343
low        319
 Low       242
Low        226
NaN        136
high        83
MEDIUM      78
Name: count, dtype: int64

Inspection Outcome
Inspection Outcome
No Defect       1171
Minor Damage    1095
Repairable       432
MINOR DAMAGE     209
no defect        202
minor damage     184
NO DEFECT        181
Major Damage     157
No Defect        148
 No Defect       140
Name: count, dtype: int64

In [24]:
numeric_columns = [
    "Value ₹",
    "Transit Days",
    "SLA hrs",
    "Resale Before ₹",
    "Resale After ₹"
]

for column in numeric_columns:
    print("\n" + "=" * 50)
    print(column)
    print("=" * 50)
    print(df[column].head(20).tolist())

==================================================
Value ₹
==================================================
[46133, 40964, 24559, '₹24,570', '33,047', 43374, 47719, '24,353', 'Rs.11203', '₹5,173', 44833, nan, ' 30076 ', '32474.0', 33083, 11640, 30770, nan, 34776, 6285]

==================================================
Transit Days
==================================================
['unknown', 2, '1', 1, 0, 0, 0, 6, 7, nan, 0, nan, 9, 8, 5, 6, 8, 1, 4, 2]

==================================================
SLA hrs
==================================================
[24, 'Rs.72', 48, 48, 48, ' 72 ', 48, 72, 72, 72, 24, 72, 72, 72, 48, 48, nan, 24, 24, 48]

==================================================
Resale Before ₹
==================================================
[42005, 38015, 19062, 'unknown', 29705, 37756, 42758, 20744, 10240, 4003, 35988, 31220, 23974, 27739, 26682, 9419, 23507, 6588, 31364, ' 5942 ']

==================================================
Resale After ₹
==================================================
[40807, 26638, 16701, 17960, '27,766', '30,581', 24459, 19608, 7245, 3989, 35348, 28071, 15359, 27501, '23062.0', ' 8217 ', 21351, 6438, 18160, 5884]

In [25]:
for column in numeric_columns:
    print("\n" + "=" * 50)
    print(column)
    print("=" * 50)
    
    print(
        df[column]
        .astype(str)
        .value_counts()
        .head(20)
    )

==================================================
Value ₹
==================================================
Value ₹
nan         128
unknown      30
none         26
-            25
0            12
44262         4
Rs.10959      3
32279         3
₹45,475       3
9982          3
9430          3
33264         3
31082         3
13307.0       3
46936         3
29933         3
39599         3
23090         3
6272          3
33085         3
Name: count, dtype: int64

==================================================
Transit Days
==================================================
Transit Days
0          986
1          799
2          592
3          451
4          369
5          290
6          241
7          188
8          142
9          125
nan        122
10          79
11          67
13          45
0.0         41
12          38
1.0         33
unknown     32
14          26
-           23
Name: count, dtype: int64

==================================================
SLA hrs
==================================================
SLA hrs
48         1552
24         1548
72         1459
nan         108
24.0         58
72.0         55
48.0         52
 24          44
48.00        36
24.00        34
72.00        33
 72          32
Rs.48        30
none         29
 48          29
unknown      27
-            24
Rs.72        23
Rs.24        22
Name: count, dtype: int64

==================================================
Resale Before ₹
==================================================
Resale Before ₹
nan        106
-           30
none        24
unknown     20
0            8
33986        4
34459        4
5158         3
5672         3
6424         3
4959         3
11527        3
10442        3
6478         3
25602        3
11537        3
5878         3
9379         3
5898         3
6651         3
Name: count, dtype: int64

==================================================
Resale After ₹
==================================================
Resale After ₹
nan        110
unknown     31
-           29
none        23
0            9
4463         3
34296        3
33046        3
23240        3
32804        3
7163         3
10880        3
19215        3
11252        3
4025         3
18872        3
3924         3
8012         3
17398        3
22395        3
Name: count, dtype: int64

In [26]:
for column in numeric_columns:
    temp = pd.to_numeric(
        df[column],
        errors="coerce"
    )
    
    print(
        column,
        "→ values that cannot be directly converted:",
        temp.isna().sum()
    )

Value ₹ → values that cannot be directly converted: 604
Transit Days → values that cannot be directly converted: 273
SLA hrs → values that cannot be directly converted: 263
Resale Before ₹ → values that cannot be directly converted: 560
Resale After ₹ → values that cannot be directly converted: 574

In [27]:
for column in numeric_columns:
    
    temp = pd.to_numeric(
        df[column],
        errors="coerce"
    )
    
    negative_count = (temp < 0).sum()
    
    print(
        column,
        "→ negative values:",
        negative_count
    )

Value ₹ → negative values: 22
Transit Days → negative values: 17
SLA hrs → negative values: 0
Resale Before ₹ → negative values: 18
Resale After ₹ → negative values: 17

In [28]:
for column in numeric_columns:
    
    temp = pd.to_numeric(
        df[column],
        errors="coerce"
    )
    
    zero_count = (temp == 0).sum()
    
    print(
        column,
        "→ zero values:",
        zero_count
    )

Value ₹ → zero values: 12
Transit Days → zero values: 1061
SLA hrs → zero values: 0
Resale Before ₹ → zero values: 11
Resale After ₹ → zero values: 12

In [29]:
resale_before = pd.to_numeric(
    df["Resale Before ₹"],
    errors="coerce"
)

resale_after = pd.to_numeric(
    df["Resale After ₹"],
    errors="coerce"
)

invalid_resale = df[
    resale_after > resale_before
]

print(
    "Rows where Resale After > Resale Before:",
    len(invalid_resale)
)

Rows where Resale After > Resale Before: 57

In [30]:
print(
    df["Return Reason"]
    .value_counts(dropna=False)
)

Return Reason
Damaged                  661
Defective                625
Wrong Product            586
Size Issue               558
Not as Expected          519
WRONG PRODUCT            116
defective                114
DEFECTIVE                106
damaged                  103
NaN                      101
DAMAGED                   99
wrong product             96
SIZE ISSUE                96
size issue                94
NOT AS EXPECTED           88
not as expected           86
 Size Issue               76
Damaged                   76
 Defective                70
 Wrong Product            69
Wrong Product             69
Size Issue                62
Defective                 55
Not As Expected           54
 Damaged                  54
Not as Expected           53
 Not as Expected          52
none                      31
unknown                   28
Not  as  Expected         21
 wrong product            21
Size  Issue               21
NOT AS EXPECTED           17
-                         16
Wrong  Product            16
 not as expected          14
 DAMAGED                  14
DEFECTIVE                 14
 WRONG PRODUCT            13
 SIZE ISSUE               12
damaged                   11
not as expected           11
 defective                10
Not As Expected            9
 size issue                9
SIZE ISSUE                 9
 NOT AS EXPECTED           9
size issue                 8
WRONG PRODUCT              8
wrong product              8
 Not As Expected           8
 Damaged                   8
DAMAGED                    8
 DEFECTIVE                 7
 damaged                   7
 Defective                 7
defective                  7
 Size Issue                6
 Wrong Product             6
 size issue                5
Size  Issue                4
 Not as Expected           4
wrong  product             4
not  as  expected          3
size  issue                3
  NOT  AS  EXPECTED        3
  Defective                3
WRONG  PRODUCT             3
NOT  AS  EXPECTED          3
  Size  Issue              2
  Not  as  Expected        2
 DEFECTIVE                 2
Not  as  Expected          2
  DEFECTIVE                2
 DAMAGED                   2
Defective                  1
Wrong  Product             1
  Damaged                  1
Not  As  Expected          1
damaged                    1
 Not As Expected           1
  Size  Issue              1
  Wrong  Product           1
Damaged                    1
 wrong product             1
 NOT AS EXPECTED           1
 not as expected           1
size  issue                1
  not  as  expected        1
SIZE  ISSUE                1
  damaged                  1
Name: count, dtype: int64

In [31]:
print(
    df["Condition Hint"]
    .value_counts(dropna=False)
)

Condition Hint
No Visible Damage       1179
Minor Scratch            208
no visible damage        200
NO VISIBLE DAMAGE        198
Wrong Fabric             183
                        ...
STAINED FABRIC             1
Pest  Damage               1
 NO VISIBLE DAMAGE         1
stained  fabric            1
  cracked  wood            1
Name: count, Length: 234, dtype: int64

In [32]:
print(
    df["Severity"]
    .value_counts(dropna=False)
)

Severity
NaN               1337
Minor              897
Moderate           486
Severe             468
NONE               194
none               190
MINOR              165
None               140
 None              137
minor              135
 Minor              98
Minor               90
MODERATE            85
moderate            75
severe              63
SEVERE              63
 Moderate           57
Moderate            56
 Severe             53
Severe              42
 none               28
NONE                25
unknown             23
-                   22
 NONE               21
none                20
 minor              15
MINOR               14
 MINOR              13
 None               13
minor               12
 Minor              12
 severe             11
Low                 11
 SEVERE             10
 moderate            9
SEVERE               9
MODERATE             8
 MODERATE            8
 Moderate            7
moderate             6
  Minor              5
 minor               5
 NONE                5
severe               4
None                 4
 Severe              3
Moderate             3
  None               3
low                  3
 none                3
LOW                  2
  Moderate           2
minor                2
Medium               2
Low                  2
 MODERATE            2
  MODERATE           2
Minor                1
NONE                 1
medium               1
  minor              1
 Low                 1
 severe              1
High                 1
  MINOR              1
  MODERATE           1
 moderate            1
  Severe             1
  Minor              1
 MINOR               1
Severe               1
 LOW                 1
Name: count, dtype: int64

In [33]:
print(
    df["Safety"]
    .value_counts(dropna=False)
)

Safety
Low           2211
Medium         451
High           434
LOW            343
low            319
 Low           242
Low            226
NaN            136
high            83
MEDIUM          78
HIGH            65
 Medium         60
medium          54
Medium          49
LOW             41
 LOW            41
 High           41
 low            37
low             34
none            32
High            29
unknown         22
-               21
high            16
 Low            16
Low             12
  Low            9
 high            9
HIGH             8
medium           7
 MEDIUM          7
Minor            6
 HIGH            6
MEDIUM           5
 Medium          4
Medium           4
 LOW             4
low              3
Severe           3
 low             3
 High            3
 medium          2
NONE             2
  High           2
Moderate         2
  Medium         1
LOW              1
moderate         1
 HIGH            1
MEDIUM           1
None             1
 medium          1
  LOW            1
minor            1
MINOR            1
  low            1
High             1
SEVERE           1
Name: count, dtype: int64

In [34]:
print(
    df["Inspection Outcome"]
    .value_counts(dropna=False)
)

Inspection Outcome
No Defect              1171
Minor Damage           1095
Repairable              432
MINOR DAMAGE            209
no defect               202
minor damage            184
NO DEFECT               181
Major Damage            157
No Defect               148
 No Defect              140
 Minor Damage           128
Scrap                   113
Minor Damage            113
NaN                      99
repairable               76
REPAIRABLE               55
Repairable               45
No  Defect               42
 Repairable              40
Minor  Damage            38
none                     28
MAJOR DAMAGE             26
no defect                24
MINOR DAMAGE             23
SCRAP                    23
 no defect               22
major damage             22
 NO DEFECT               22
scrap                    21
-                        21
NO DEFECT                20
 Major Damage            19
 minor damage            17
 Minor Damage            17
minor damage             16
Scrap                    16
unknown                  16
 MINOR DAMAGE            14
repairable               13
NO  DEFECT               12
 No Defect               12
 REPAIRABLE              11
 Scrap                   10
Major Damage              9
 Repairable               8
Minor  Damage             7
  Minor  Damage           7
  No  Defect              6
MINOR  DAMAGE             5
REPAIRABLE                5
MAJOR DAMAGE              4
Major  Damage             4
 scrap                    4
minor  damage             4
 repairable               3
No  Defect                3
Repairable                2
 minor damage             2
SCRAP                     2
 MAJOR DAMAGE             2
 Scrap                    2
 REPAIRABLE               2
 major damage             2
 MINOR DAMAGE             2
 major damage             2
  Scrap                   1
no  defect                1
minor  damage             1
  Minor  Damage           1
  MINOR  DAMAGE           1
major damage              1
 scrap                    1
Major  Damage             1
MAJOR  DAMAGE             1
scrap                     1
  REPAIRABLE              1
  MAJOR  DAMAGE           1
NO  DEFECT                1
 NO DEFECT                1
no  defect                1
Name: count, dtype: int64

In [35]:
print("=" * 60)
print("           DATA QUALITY SUMMARY")
print("=" * 60)

print("Rows                  :", df.shape[0])
print("Columns               :", df.shape[1])
print("Exact duplicates      :", df.duplicated().sum())
print("Duplicate Return IDs  :", df["Return ID"].duplicated().sum())
print("Total missing values  :", df.isnull().sum().sum())

print("\nColumn data types:")
print(df.dtypes)

============================================================
           DATA QUALITY SUMMARY
============================================================
Rows                  : 5195
Columns               : 12
Exact duplicates      : 137
Duplicate Return IDs  : 138
Total missing values  : 2479

Column data types:
Return ID             object
Product               object
Value ₹               object
Transit Days          object
Return Reason         object
Condition Hint        object
Severity              object
Safety                object
SLA hrs               object
Inspection Outcome    object
Resale Before ₹       object
Resale After ₹        object
dtype: object

In [36]:
quality_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Missing Count": df.isnull().sum().values,
    "Missing %": (
        df.isnull().sum() / len(df) * 100
    ).round(2).values,
    "Unique Values": [
        df[col].nunique(dropna=False)
        for col in df.columns
    ]
})

quality_summary

                Column Data Type  Missing Count  Missing %  Unique Values
0            Return ID    object             15       0.29           5057
1              Product    object            103       1.98            110
2              Value ₹    object            128       2.46           4619
3         Transit Days    object            122       2.35            123
4        Return Reason    object            101       1.94             91
5       Condition Hint    object            114       2.19            234
6             Severity    object           1337      25.74             73
7               Safety    object            136       2.62             58
8              SLA hrs    object            108       2.08             22
9   Inspection Outcome    object             99       1.91             80
10     Resale Before ₹    object            106       2.04           4600
11      Resale After ₹    object            110       2.12           4591