In [151]:
import pandas as pd
import numpy as np

In [152]:
file_path = "../data/Processed/furniture_returns_cleaned.xlsx"

df = pd.read_excel(file_path)

print("Cleaned dataset loaded successfully!")
print("Dataset shape:", df.shape)

Cleaned dataset loaded successfully!
Dataset shape: (5058, 14)

In [153]:
df.head()

,Return ID,Product,Value ₹,Transit Days,Return Reason,Condition Hint,Severity,Safety,SLA hrs,Inspection Outcome,Resale Before ₹,Resale After ₹,Value Loss ₹,Value Loss %
0,R-3047,bed,46133,2,size issue,no visible damage,unknown,low,24,no defect,42005,40807,1198,2.852041
1,R2886,bed,40964,2,damaged,torn fabric,medium,high,48,repairable,38015,26638,11377,29.927660
2,R2747,unknown,24559,1,damaged,chipped surface,medium,low,48,minor damage,19062,16701,2361,12.385899
3,R4670,dining table,26326,1,defective,loose joints,low,low,48,minor damage,21997,17960,4037,18.352503
4,R4898,dining table,26326,0,not as expected,color mismatch,low,low,48,minor damage,29705,18165,11540,38.848679

In [154]:
print("Columns in dataset:")

for column in df.columns:
    print("-", column)

Columns in dataset:
- Return ID
- Product
- Value ₹
- Transit Days
- Return Reason
- Condition Hint
- Severity
- Safety
- SLA hrs
- Inspection Outcome
- Resale Before ₹
- Resale After ₹
- Value Loss ₹
- Value Loss %

In [155]:
important_columns = [
    "Return ID",
    "Product",
    "Value ₹",
    "Transit Days",
    "Condition Hint",
    "Severity",
    "Safety",
    "SLA hrs",
    "Inspection Outcome",
    "Resale Before ₹",
    "Resale After ₹",
    "Value Loss ₹",
    "Value Loss %"
]

df[important_columns].head(10)

,Return ID,Product,Value ₹,Transit Days,Condition Hint,Severity,Safety,SLA hrs,Inspection Outcome,Resale Before ₹,Resale After ₹,Value Loss ₹,Value Loss %
0,R-3047,bed,46133,2,no visible damage,unknown,low,24,no defect,42005,40807,1198,2.852041
1,R2886,bed,40964,2,torn fabric,medium,high,48,repairable,38015,26638,11377,29.927660
2,R2747,unknown,24559,1,chipped surface,medium,low,48,minor damage,19062,16701,2361,12.385899
3,R4670,dining table,26326,1,loose joints,low,low,48,minor damage,21997,17960,4037,18.352503
4,R4898,dining table,26326,0,color mismatch,low,low,48,minor damage,29705,18165,11540,38.848679
5,R2596,bed,43374,0,faulty hinge,high,high,72,repairable,37756,18165,19591,51.888442
6,R3729,sofa,47719,0,chipped surface,high,medium,48,scrap,42758,24459,18299,42.796670
7,R3755,wardrobe,26326,6,cushion damage,low,medium,72,minor damage,20744,19608,1136,5.476282
8,R3354,coffee table,26326,7,cushion damage,medium,unknown,72,repairable,10240,7245,2995,29.248047
9,r79,chair,26326,2,no visible damage,unknown,low,72,no defect,4003,3989,14,0.349738

In [156]:
df["Value Loss ₹"] = (
    df["Resale Before ₹"]
    - df["Resale After ₹"]
)

df["Value Loss ₹"].head()

0     1198
1    11377
2     2361
3     4037
4    11540
Name: Value Loss ₹, dtype: int64

In [157]:
df["Value Loss %"] = np.where(
    df["Resale Before ₹"] > 0,
    (
        df["Value Loss ₹"]
        / df["Resale Before ₹"]
    ) * 100,
    0
)

df["Value Loss %"] = df["Value Loss %"].round(2)

df[
    [
        "Resale Before ₹",
        "Resale After ₹",
        "Value Loss ₹",
        "Value Loss %"
    ]
].head(10)

   Resale Before ₹  Resale After ₹  Value Loss ₹  Value Loss %
0            42005           40807          1198          2.85
1            38015           26638         11377         29.93
2            19062           16701          2361         12.39
3            21997           17960          4037         18.35
4            29705           18165         11540         38.85
5            37756           18165         19591         51.89
6            42758           24459         18299         42.80
7            20744           19608          1136          5.48
8            10240            7245          2995         29.25
9             4003            3989            14          0.35

In [158]:
print(df["Severity"].value_counts(dropna=False))

Severity
unknown    2096
low        1461
medium      790
high        711
Name: count, dtype: int64

In [159]:
severity_map = {
    "low": 1,
    "medium": 2,
    "high": 3,
    "unknown": 1
}

df["Severity Score"] = (
    df["Severity"]
    .map(severity_map)
    .fillna(1)
)

df[
    [
        "Severity",
        "Severity Score"
    ]
].head(10)

  Severity  Severity Score
0  unknown               1
1   medium               2
2   medium               2
3      low               1
4      low               1
5     high               3
6     high               3
7      low               1
8   medium               2
9  unknown               1

In [160]:
print(df["Safety"].value_counts(dropna=False))

Safety
low        3467
medium      710
high        687
unknown     194
Name: count, dtype: int64

In [161]:
safety_map = {
    "low": 1,
    "medium": 2,
    "high": 3,
    "unknown": 1
}

df["Safety Score"] = (
    df["Safety"]
    .map(safety_map)
    .fillna(1)
)

df[
    [
        "Safety",
        "Safety Score"
    ]
].head(10)

    Safety  Safety Score
0      low             1
1     high             3
2      low             1
3      low             1
4      low             1
5     high             3
6   medium             2
7   medium             2
8  unknown             1
9      low             1

In [162]:
print(df["Condition Hint"].value_counts(dropna=False))

Condition Hint
no visible damage    1947
minor scratch         343
wrong fabric          297
color mismatch        296
broken frame          258
door misalignment     229
faulty hinge          194
cushion damage        191
loose joints          186
unknown               165
cracked glass         100
torn fabric            94
water damage           92
chipped surface        91
cracked wood           90
broken leg             90
broken shelf           90
structural crack       84
stained fabric         78
scratched surface      75
pest damage            68
Name: count, dtype: int64

In [163]:
condition_risk_map = {
    
    # Low Risk
    "no visible damage": 1,
    "minor scratch": 1,
    "scratched surface": 1,
    "color mismatch": 1,
    "wrong fabric": 1,
    "stained fabric": 1,
    "chipped surface": 1,
    "cosmetic damage": 1,
    
    # Medium Risk
    "dent": 2,
    "door misalignment": 2,
    "faulty hinge": 2,
    "loose joints": 2,
    "loose parts": 2,
    "cushion damage": 2,
    "torn fabric": 2,
    "water damage": 2,
    "pest damage": 2,
    
    # High Risk
    "broken frame": 3,
    "broken leg": 3,
    "broken shelf": 3,
    "cracked glass": 3,
    "cracked wood": 3,
    "structural crack": 3,
    "structural damage": 3,
    "severe damage": 3,
    
    # Unknown
    "unknown": 1,
    "Unknown": 1,
    "none": 1,
    "-": 1
}

df["Condition Risk Score"] = (
    df["Condition Hint"]
    .map(condition_risk_map)
    .fillna(1)
)

print("Condition Hint and Risk Score:")

print(
    df[
        [
            "Condition Hint",
            "Condition Risk Score"
        ]
    ].head(10)
)

Condition Hint and Risk Score:
      Condition Hint  Condition Risk Score
0  no visible damage                     1
1        torn fabric                     2
2    chipped surface                     1
3       loose joints                     2
4     color mismatch                     1
5       faulty hinge                     2
6    chipped surface                     1
7     cushion damage                     2
8     cushion damage                     2
9  no visible damage                     1

In [164]:
def transit_risk(days):

    if days <= 2:
        return 1

    elif days <= 5:
        return 2

    elif days <= 10:
        return 3

    else:
        return 4


df["Transit Risk Score"] = (
    df["Transit Days"]
    .apply(transit_risk)
)

df[
    [
        "Transit Days",
        "Transit Risk Score"
    ]
].head(10)

   Transit Days  Transit Risk Score
0             2                   1
1             2                   1
2             1                   1
3             1                   1
4             0                   1
5             0                   1
6             0                   1
7             6                   3
8             7                   3
9             2                   1

In [165]:
def assign_value_loss_risk(value_loss_percent):
    
    if value_loss_percent >= 50:
        return 3
    elif value_loss_percent >= 25:
        return 2
    else:
        return 1


df["Value Loss Risk Score"] = (
    df["Value Loss %"]
    .apply(assign_value_loss_risk)
)

print(
    df[
        [
            "Value Loss %",
            "Value Loss Risk Score"
        ]
    ].head(10)
)

   Value Loss %  Value Loss Risk Score
0          2.85                      1
1         29.93                      2
2         12.39                      1
3         18.35                      1
4         38.85                      2
5         51.89                      3
6         42.80                      2
7          5.48                      1
8         29.25                      2
9          0.35                      1

In [166]:
def assign_sla_urgency(sla_hours):
    
    if sla_hours <= 24:
        return 3
    elif sla_hours <= 48:
        return 2
    else:
        return 1


df["SLA Urgency Score"] = (
    df["SLA hrs"]
    .apply(assign_sla_urgency)
)

print(
    df[
        [
            "SLA hrs",
            "SLA Urgency Score"
        ]
    ].head(10)
)

   SLA hrs  SLA Urgency Score
0       24                  3
1       48                  2
2       48                  2
3       48                  2
4       48                  2
5       72                  1
6       48                  2
7       72                  1
8       72                  1
9       72                  1

In [167]:
score_columns = [
    "Value Loss ₹",
    "Value Loss %",
    "Value Loss Risk Score",
    "Severity Score",
    "Safety Score",
    "Condition Risk Score",
    "Transit Risk Score",
    "SLA Urgency Score"
]

print("Missing values in engineered features:\n")

print(
    df[score_columns]
    .isnull()
    .sum()
)

Missing values in engineered features:

Value Loss ₹             0
Value Loss %             0
Value Loss Risk Score    0
Severity Score           0
Safety Score             0
Condition Risk Score     0
Transit Risk Score       0
SLA Urgency Score        0
dtype: int64

In [168]:
def sla_urgency(hours):

    if hours <= 24:
        return 4

    elif hours <= 48:
        return 3

    elif hours <= 72:
        return 2

    else:
        return 1


df["SLA Urgency Score"] = (
    df["SLA hrs"]
    .apply(sla_urgency)
)

df[
    [
        "SLA hrs",
        "SLA Urgency Score"
    ]
].head(10)

   SLA hrs  SLA Urgency Score
0       24                  4
1       48                  3
2       48                  3
3       48                  3
4       48                  3
5       72                  2
6       48                  3
7       72                  2
8       72                  2
9       72                  2

In [169]:
def value_loss_risk(loss_percentage):

    if loss_percentage < 10:
        return 1

    elif loss_percentage < 25:
        return 2

    elif loss_percentage < 50:
        return 3

    else:
        return 4


df["Value Loss Risk Score"] = (
    df["Value Loss %"]
    .apply(value_loss_risk)
)

df[
    [
        "Value Loss %",
        "Value Loss Risk Score"
    ]
].head(10)

   Value Loss %  Value Loss Risk Score
0          2.85                      1
1         29.93                      3
2         12.39                      2
3         18.35                      2
4         38.85                      3
5         51.89                      4
6         42.80                      3
7          5.48                      1
8         29.25                      3
9          0.35                      1

In [170]:
df["Priority Score"] = (

    df["Value Loss Risk Score"] * 0.30 +

    df["Severity Score"] * 0.20 +

    df["Safety Score"] * 0.20 +

    df["Transit Risk Score"] * 0.15 +

    df["SLA Urgency Score"] * 0.10 +

    df["Condition Risk Score"] * 0.05
)

df["Priority Score"] = df["Priority Score"].round(2)

df[
    [
        "Value Loss Risk Score",
        "Severity Score",
        "Safety Score",
        "Transit Risk Score",
        "SLA Urgency Score",
        "Condition Risk Score",
        "Priority Score"
    ]
].head(10)

,Value Loss Risk Score,Severity Score,Safety Score,Transit Risk Score,SLA Urgency Score,Condition Risk Score,Priority Score
0,1,1,1,1,4,1,1.30
1,3,2,3,1,3,2,2.45
2,2,2,1,1,3,1,1.70
3,2,1,1,1,3,2,1.55
4,3,1,1,1,3,1,1.80
5,4,3,3,1,2,2,2.85
6,3,3,2,1,3,1,2.40
7,1,1,2,3,2,2,1.65
8,3,2,1,3,2,2,2.25
9,1,1,1,1,2,1,1.10

In [171]:
def assign_priority(score):

    if score >= 3.0:
        return "High"

    elif score >= 2.0:
        return "Medium"

    else:
        return "Low"

In [172]:
df["Priority"] = (
    df["Priority Score"]
    .apply(assign_priority)
)

print(df["Priority"].value_counts())

Priority
Low       3602
Medium    1378
High        78
Name: count, dtype: int64

In [173]:
def create_evidence(row):

    reasons = []

    if row["Value Loss Risk Score"] >= 3:
        reasons.append("High resale value loss")

    if row["Severity Score"] >= 3:
        reasons.append("High damage severity")

    if row["Safety Score"] >= 3:
        reasons.append("High safety risk")

    if row["Transit Risk Score"] >= 3:
        reasons.append("Long transit time")

    if row["SLA Urgency Score"] >= 3:
        reasons.append("Urgent SLA")

    if row["Condition Risk Score"] >= 3:
        reasons.append("Serious condition issue")

    if not reasons:
        reasons.append("Standard inspection priority")

    return "; ".join(reasons)


df["Priority Evidence"] = (
    df.apply(create_evidence, axis=1)
)

df[
    [
        "Return ID",
        "Priority",
        "Priority Score",
        "Priority Evidence"
    ]
].head(10)

,Return ID,Priority,Priority Score,Priority Evidence
0,R-3047,Low,1.30,Urgent SLA
1,R2886,Medium,2.45,High resale value loss; High safety risk; Urge...
2,R2747,Low,1.70,Urgent SLA
3,R4670,Low,1.55,Urgent SLA
4,R4898,Low,1.80,High resale value loss; Urgent SLA
5,R2596,Medium,2.85,High resale value loss; High damage severity; ...
6,R3729,Medium,2.40,High resale value loss; High damage severity; ...
7,R3755,Low,1.65,Long transit time
8,R3354,Medium,2.25,High resale value loss; Long transit time
9,r79,Low,1.10,Standard inspection priority

In [174]:
high_priority = df[
    df["Priority"] == "High"
]

high_priority[
    [
        "Return ID",
        "Product",
        "Value ₹",
        "Transit Days",
        "Severity",
        "Safety",
        "Value Loss %",
        "Priority Score",
        "Priority Evidence"
    ]
].head(20)

,Return ID,Product,Value ₹,Transit Days,Severity,Safety,Value Loss %,Priority Score,Priority Evidence
124,R2307,bookshelf,26326,10,high,high,47.44,3.00,High resale value loss; High damage severity; ...
146,r2888,chair,6468,6,high,high,34.27,3.00,High resale value loss; High damage severity; ...
194,R1758,sofa,49846,16,medium,high,57.35,3.30,High resale value loss; High safety risk; Long...
274,R4084,wardrobe,26326,9,high,medium,59.50,3.05,High resale value loss; High damage severity; ...
298,R3033,coffee table,26326,3,high,medium,70.66,3.00,High resale value loss; High damage severity; ...
314,R0475,chair,5616,2,high,high,57.00,3.00,High resale value loss; High damage severity; ...
383,R0460,bed,43938,16,high,high,48.45,3.10,High resale value loss; High damage severity; ...
414,R1570,dining table,31913,1,high,high,51.97,3.00,High resale value loss; High damage severity; ...
478,R0767,sofa,40012,1,high,high,59.27,3.00,High resale value loss; High damage severity; ...
489,R4875,dining table,35522,7,high,high,30.39,3.00,High resale value loss; High damage severity; ...
570,R3534,wardrobe,22844,19,high,high,34.80,3.00,High resale value loss; High damage severity; ...
646,R0980,sofa,54891,12,high,high,48.92,3.00,High resale value loss; High damage severity; ...
651,R1356,bookshelf,7997,11,high,high,42.45,3.05,High resale value loss; High damage severity; ...
702,R0774,coffee table,26326,7,high,high,54.21,3.20,High resale value loss; High damage severity; ...
940,R1732,bookshelf,10108,16,high,low,78.19,3.15,High resale value loss; High damage severity; ...
1002,R0314,chair,6729,6,high,high,53.23,3.25,High resale value loss; High damage severity; ...
1013,R4813,bed,49554,10,high,medium,52.93,3.15,High resale value loss; High damage severity; ...
1067,R1123,sofa,44653,7,medium,high,54.62,3.00,High resale value loss; High safety risk; Long...
1094,R3533,bed,47053,6,high,high,53.01,3.15,High resale value loss; High damage severity; ...
1126,R-4849,coffee table,17830,7,high,high,29.89,3.10,High resale value loss; High damage severity; ...

In [175]:
priority_summary = pd.DataFrame({
    "Count": df["Priority"].value_counts(),
    "Percentage": (
        df["Priority"]
        .value_counts(normalize=True)
        * 100
    ).round(2)
})

priority_summary

          Count  Percentage
Priority
Low        3602       71.21
Medium     1378       27.24
High         78        1.54

In [176]:
feature_columns = [
    "Value Loss ₹",
    "Value Loss %",
    "Severity Score",
    "Safety Score",
    "Condition Risk Score",
    "Transit Risk Score",
    "SLA Urgency Score",
    "Value Loss Risk Score",
    "Priority Score",
    "Priority",
    "Priority Evidence"
]

df[feature_columns].head(10)

,Value Loss ₹,Value Loss %,Severity Score,Safety Score,Condition Risk Score,Transit Risk Score,SLA Urgency Score,Value Loss Risk Score,Priority Score,Priority,Priority Evidence
0,1198,2.85,1,1,1,1,4,1,1.30,Low,Urgent SLA
1,11377,29.93,2,3,2,1,3,3,2.45,Medium,High resale value loss; High safety risk; Urge...
2,2361,12.39,2,1,1,1,3,2,1.70,Low,Urgent SLA
3,4037,18.35,1,1,2,1,3,2,1.55,Low,Urgent SLA
4,11540,38.85,1,1,1,1,3,3,1.80,Low,High resale value loss; Urgent SLA
5,19591,51.89,3,3,2,1,2,4,2.85,Medium,High resale value loss; High damage severity; ...
6,18299,42.80,3,2,1,1,3,3,2.40,Medium,High resale value loss; High damage severity; ...
7,1136,5.48,1,2,2,3,2,1,1.65,Low,Long transit time
8,2995,29.25,2,1,2,3,2,3,2.25,Medium,High resale value loss; Long transit time
9,14,0.35,1,1,1,1,2,1,1.10,Low,Standard inspection priority

In [177]:
output_path = "../data/Processed/furniture_returns_featured.xlsx"

df.to_excel(
    output_path,
    index=False
)

print("Feature engineered dataset saved successfully!")
print(output_path)

Feature engineered dataset saved successfully!
../data/Processed/furniture_returns_featured.xlsx

In [178]:
print("=" * 60)
print("FEATURE ENGINEERING SUMMARY")
print("=" * 60)

print("Dataset Shape:", df.shape)

print("\nPriority Distribution:")
print(df["Priority"].value_counts())

print("\nNew Features Created:")

for column in feature_columns:
    print("-", column)

============================================================
FEATURE ENGINEERING SUMMARY
============================================================
Dataset Shape: (5058, 23)

Priority Distribution:
Priority
Low       3602
Medium    1378
High        78
Name: count, dtype: int64

New Features Created:
- Value Loss ₹
- Value Loss %
- Severity Score
- Safety Score
- Condition Risk Score
- Transit Risk Score
- SLA Urgency Score
- Value Loss Risk Score
- Priority Score
- Priority
- Priority Evidence